<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Custom Report - {{ $reportType }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 9pt;
            line-height: 1.4;
            color: #1f2937;
        }

        .page-break {
            page-break-after: always;
        }

        /* Header */
        .header {
            border-bottom: 3px solid #3b82f6;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }

        .header h1 {
            font-size: 20pt;
            font-weight: bold;
            color: #1e3a8a;
            margin-bottom: 5px;
        }

        .header .subtitle {
            font-size: 11pt;
            color: #6b7280;
        }

        .header .generated-info {
            font-size: 9pt;
            color: #9ca3af;
            margin-top: 8px;
        }

        /* Filter Info */
        .filter-info {
            background-color: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 4px;
            padding: 10px 15px;
            margin-bottom: 20px;
        }

        .filter-info .label {
            font-size: 9pt;
            color: #6b7280;
            font-weight: bold;
        }

        .filter-info .value {
            font-size: 9pt;
            color: #1f2937;
        }

        /* Summary Stats */
        .summary-stats {
            margin-bottom: 20px;
            text-align: right;
        }

        .summary-stats .total {
            font-size: 10pt;
            color: #6b7280;
        }

        .summary-stats .total strong {
            color: #1f2937;
        }

        /* Data Table */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 8pt;
        }

        .data-table th {
            background-color: #3b82f6;
            color: white;
            font-weight: bold;
            padding: 8px 6px;
            text-align: left;
            border: 1px solid #2563eb;
        }

        .data-table td {
            padding: 6px;
            border: 1px solid #e5e7eb;
            vertical-align: top;
        }

        .data-table tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .data-table tr:hover {
            background-color: #f3f4f6;
        }

        /* Group Header Row */
        .group-header {
            background-color: #dbeafe !important;
            border-left: 4px solid #3b82f6;
        }

        .group-header td {
            font-weight: bold;
            color: #1e40af;
            padding: 10px 6px;
            font-size: 9pt;
        }

        /* Group Subtotal Row */
        .group-subtotal {
            background-color: #f0f9ff !important;
            border-top: 2px solid #93c5fd;
        }

        .group-subtotal td {
            font-weight: bold;
            font-style: italic;
            color: #374151;
            padding: 8px 6px;
            font-size: 8pt;
        }

        /* Numeric Columns */
        .data-table .numeric {
            text-align: right;
        }

        /* Footer */
        .footer {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8pt;
            color: #9ca3af;
        }

        .footer .page-number:before {
            content: counter(page);
        }

        /* Empty State */
        .empty-state {
            text-align: center;
            padding: 40px;
            color: #6b7280;
        }

        .empty-state p {
            font-size: 11pt;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>{{ $reportType }}</h1>
        <div class="subtitle">Custom Report Builder Export</div>
        <div class="generated-info">
            Generated by {{ $generatedBy }} on {{ $generatedAt->format('F j, Y \a\t g:i A') }}
        </div>
    </div>

    <!-- Filter Information -->
    <div class="filter-info">
        <span class="label">Filters Applied:</span>
        <span class="value">{{ $filters }}</span>
        @if($groupBy)
            <br>
            <span class="label">Grouped By:</span>
            <span class="value">{{ $groupBy }}</span>
        @endif
    </div>

    <!-- Summary Stats -->
    <div class="summary-stats">
        <span class="total">Total Records: <strong>{{ $total }}</strong></span>
    </div>

    <!-- Data Table -->
    @if(count($data) > 0)
        @if($groupBy && isset($groupedData) && count($groupedData) > 0)
            {{-- Grouped Data Display --}}
            @foreach($groupedData as $groupName => $groupItems)
                {{-- Group Header --}}
                <table class="data-table" style="margin-bottom: 20px;">
                    <thead>
                        <tr class="group-header">
                            <td colspan="{{ count($columns) }}">
                                {{ $groupBy }}: {{ $groupName ?? 'Unassigned' }}
                                <span style="float: right; font-size: 8pt; font-weight: normal;">
                                    ({{ count($groupItems) }} {{ count($groupItems) === 1 ? 'record' : 'records' }})
                                </span>
                            </td>
                        </tr>
                        <tr>
                            @foreach($columns as $column)
                                <th>{{ $column['label'] }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($groupItems as $row)
                            <tr>
                                @foreach($columns as $column)
                                    @php
                                        $value = $row[$column['key']] ?? '-';
                                        $isNumeric = is_numeric($value);
                                    @endphp
                                    <td class="{{ $isNumeric ? 'numeric' : '' }}">{{ $value }}</td>
                                @endforeach
                            </tr>
                        @endforeach
                        {{-- Group Subtotal Row --}}
                        @if(isset($groupSubtotals[$groupName]))
                            <tr class="group-subtotal">
                                @foreach($columns as $index => $column)
                                    @if($index === 0)
                                        <td>Subtotal</td>
                                    @elseif(isset($groupSubtotals[$groupName][$column['key']]))
                                        <td class="numeric">{{ $groupSubtotals[$groupName][$column['key']] }}</td>
                                    @else
                                        <td></td>
                                    @endif
                                @endforeach
                            </tr>
                        @endif
                    </tbody>
                </table>
            @endforeach
        @else
            {{-- Non-Grouped Data Display --}}
            <table class="data-table">
                <thead>
                    <tr>
                        @foreach($columns as $column)
                            <th>{{ $column['label'] }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $row)
                        <tr>
                            @foreach($columns as $column)
                                @php
                                    $value = $row[$column['key']] ?? '-';
                                    $isNumeric = is_numeric($value);
                                @endphp
                                <td class="{{ $isNumeric ? 'numeric' : '' }}">{{ $value }}</td>
                            @endforeach
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    @else
        <div class="empty-state">
            <p>No data found matching the selected criteria.</p>
        </div>
    @endif

    <!-- Footer -->
    <div class="footer">
        <span>RackAudit Custom Report - {{ $reportType }}</span>
        <span> | </span>
        <span>Page <span class="page-number"></span></span>
    </div>
</body>
</html>
