<?php

namespace Database\Factories;

use App\Models\Audit;
use App\Models\AuditReport;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Factory for generating AuditReport test data.
 *
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\AuditReport>
 */
class AuditReportFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\Illuminate\Database\Eloquent\Model>
     */
    protected $model = AuditReport::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $auditId = fake()->numberBetween(1, 1000);
        $timestamp = fake()->dateTimeBetween('-1 month', 'now')->format('YmdHis');

        return [
            'audit_id' => Audit::factory(),
            'user_id' => User::factory(),
            'file_path' => "reports/audits/audit-report-{$auditId}-{$timestamp}.pdf",
            'generated_at' => fake()->dateTimeBetween('-1 month', 'now'),
            'file_size_bytes' => fake()->numberBetween(50000, 5000000),
        ];
    }

    /**
     * Create a report for a specific audit.
     */
    public function forAudit(Audit $audit): static
    {
        return $this->state(function (array $attributes) use ($audit) {
            $timestamp = fake()->dateTimeBetween('-1 month', 'now')->format('YmdHis');

            return [
                'audit_id' => $audit->id,
                'file_path' => "reports/audits/audit-report-{$audit->id}-{$timestamp}.pdf",
            ];
        });
    }

    /**
     * Create a report generated by a specific user.
     */
    public function generatedBy(User $user): static
    {
        return $this->state(fn (array $attributes) => [
            'user_id' => $user->id,
        ]);
    }

    /**
     * Create a report with a specific file size.
     */
    public function withFileSize(int $bytes): static
    {
        return $this->state(fn (array $attributes) => [
            'file_size_bytes' => $bytes,
        ]);
    }

    /**
     * Create a small report (under 100KB).
     */
    public function small(): static
    {
        return $this->state(fn (array $attributes) => [
            'file_size_bytes' => fake()->numberBetween(10000, 100000),
        ]);
    }

    /**
     * Create a large report (over 1MB).
     */
    public function large(): static
    {
        return $this->state(fn (array $attributes) => [
            'file_size_bytes' => fake()->numberBetween(1000000, 10000000),
        ]);
    }

    /**
     * Create a report generated at a specific time.
     */
    public function generatedAt(\DateTimeInterface|string $datetime): static
    {
        return $this->state(fn (array $attributes) => [
            'generated_at' => $datetime,
        ]);
    }

    /**
     * Create a recently generated report (within the last 24 hours).
     */
    public function recent(): static
    {
        return $this->state(fn (array $attributes) => [
            'generated_at' => fake()->dateTimeBetween('-24 hours', 'now'),
        ]);
    }
}
