<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * AuditReport model representing a generated PDF report for an audit.
 *
 * Reports are generated by users and stored for historical access.
 * They contain executive summaries, findings by severity, and
 * connection comparison results (for connection-type audits).
 */
class AuditReport extends Model
{
    /** @use HasFactory<\Database\Factories\AuditReportFactory> */
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'audit_id',
        'user_id',
        'file_path',
        'generated_at',
        'file_size_bytes',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'generated_at' => 'datetime',
            'file_size_bytes' => 'integer',
        ];
    }

    /**
     * Get the audit this report belongs to.
     */
    public function audit(): BelongsTo
    {
        return $this->belongsTo(Audit::class);
    }

    /**
     * Get the user who generated this report.
     */
    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
